### ISSUE TITLE
NPF Spec - TOC has a broken link to a missing section

### ISSUE THREAD

**Issue by highthunder** [tumblr/docs#16] opened 2020-07-05 22:52 UTC
The `Inline Format Type: Size` section was removed in commit [340c9d9](https://github.com/tumblr/docs/commit/340c9d955cc1ec0ce55e0849e2a458905f781b09) however the table of contents still has a (now broken) link to that section.

Aside: Is the `size` type still on the roadmap to be implemented in the future?

**Comment by nightpool** [comment] 2020-07-05 22:58
I know small formatting was added last week, but I believe it uses a different API structure then the commit you linked.

**Comment by nightpool** [comment] 2020-07-05 23:17
Right now it seems like it's only available to internal API clients (is this intentional, @cyle?), but currently it looks like this:

```json
{
  "content": [
    {
      "type": "text",
      "text": "this is a test of the small formatting",
      "formatting": [
        {
          "type": "small",
          "start": 0,
          "end": 38
        }
      ]
    }
  ]
}
```

**Comment by nightpool** [comment] 2020-07-05 23:18
(i got this by inspecting the dash for a small-formatted post—the post needs to use the <small> tag specifically, not <sub> or <sup>, which are also in common use in legacy posts)

**Comment by nightpool** [comment] 2020-07-05 23:18
(i got this by inspecting the dash for a small-formatted post—the post needs to use the `<small>` tag specifically, not `<sub>` or `<sup>`, which are also in common use in legacy posts)

**Comment by cyle** [comment] 2020-07-06 15:01
Hello! A few things:

- Thanks for pointing out the broken link, I'll fix that up. 👌 
- `Inline Format Type: Size` is something we were testing internally and was scrapped, we have no current plans to implement it.
- `Inline Format Type: Small` was what we ended up with instead, to better match the expectation of how `<small>` worked on the legacy web dashboard, as @nightpool suggested.
- `type: small` is currently only available to our official API clients, but I can open that up to third party API consumers as well. I need to update the NPF spec docs here with this new inline type, so I'll do that, too.
- We have no current plans to build support for other inline styles (such as ones that would work with `<sub>` and `<sup>`), though plans can change. If they do get built, you'll likely see an update to the NPF specs here.

I'll close this issue once the docs are updated. Thanks!

**Comment by cyle** [comment] 2020-07-07 15:28
Updated! https://github.com/tumblr/docs/blob/master/npf-spec.md#inline-format-types-bold-italic-strikethrough-small

Thanks again!

**Closed by cyle** 2020-07-07 15:28 UTC

**Comment by highthunder** [comment] 2020-07-11 13:42
Wow, I didn't expect to get a new feature turned on just by bringing up some broken formatting.

One question: What is the intended behavior of overlapping `small` formats?

The website doesn't seem to handle them consistently:

1. When viewing a post on www.tumblr.com/blog/blogName, the size is only decreased once
2. When viewing a post on blogname.tumblr.com, the size is decreased for every format

Although the HTML has a bunch of nested `<small>` tags on both pages, so maybe this is just a CSS bug on www.tumblr.com/blog/blogName?

**Comment by cyle** [comment] 2020-07-13 15:34
> One question: What is the intended behavior of overlapping small formats?

The intended behavior is for all of them to be the same small size, so you could overlap several `small` inline formatting ranges but they will all be the same size when rendered inside of Tumblr. The behavior on www.tumblr.com is what's intended; the handling in the blog theme, however, is likely a bug. Thanks for pointing it out!
